spring:
  datasource:
    url: jdbc:mysql://localhost:3306/login
    username: root
    password: admin1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: com.abstractionizer.login.uuid1/db/rmdb/mappers/*Mapper.xml

redis:
  port: 6379
  host: localhost
  pool:
    maxIdle: 8
    minIdle: 0
    maxActive: -1
    maxWait: 30000